[project]
name = "local-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "openpyxl>=3.1.0",
    "pandas>=2.0.0",
    "python-dateutil>=2.8.0",
    "requests>=2.28.0",
]
